sudo: true
language: ruby
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem install bundler:"$BUNDLER_VERSION"
  - sudo apt-get -qq install graphviz
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0 
  - export PATH="$HOME/.yarn/bin:$PATH"
rvm:
  - 2.5.1
env:
  - BUNDLER_VERSION=1.15.4
  - BUNDLER_VERSION=1.16.3
